#!/bin/env bash
export Path="$(pwd)"
export AFHOME="AF_HOME_Path"
if [ -e $AFHOME ]
then
  source $AFHOME/config
fi
if [ -n $@ ]
then
  CheckInstall $1
  case $1 in
  YN|Yunzai-Next)
    StartCommand="node src/main"
    Pm2Name="yunzai-next"
    ;;
  MZ|Miao-Yunzai)
    StartCommand="node app"
    Pm2Name="Miao-Yunzai"
    ;;
  TZ|TRSS-Yunzai)
    StartCommand="node app"
    Pm2Name="TRSS-Yunzai"
    ;;
  esac
  START "${StartCommand}" ${Pm2Name}
  exit 0
fi
cd ${AFHOME}/Manage
bash Main "$@"